# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
version: 2
jobs:
  test:
    parallelism: 1
    docker:
      - image: circleci/ruby:2.5
    working_directory: ~/activerecord-snapshot
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake
      - store_test_results:
          path: test_results

workflows:
  version: 2
  circleci:
    jobs:
      - test
