# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details 
version: 2
jobs:
  test:
    parallelism: 1
    docker:
      - image: circleci/ruby:2.5
    working_directory: ~/activerecord-snapshot
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
      - run: bundle check --path vendor/bundle || bundle install --frozen --path vendor/bundle
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec rake test
      - store_test_results:
          path: test_results

workflows:
  version: 2
  circleci:
    jobs:
      - test
